//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpineForge.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpineForge.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 转换完成! 的本地化字符串。
        /// </summary>
        internal static string ConversionComplete {
            get {
                return ResourceManager.GetString("ConversionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换错误: {0} 的本地化字符串。
        /// </summary>
        internal static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换成功完成! 的本地化字符串。
        /// </summary>
        internal static string Log_ConversionSuccess {
            get {
                return ResourceManager.GetString("Log_ConversionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 JSON 后处理... 的本地化字符串。
        /// </summary>
        internal static string Log_JsonPostProcessing {
            get {
                return ResourceManager.GetString("Log_JsonPostProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_Output {
            get {
                return ResourceManager.GetString("Log_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出目录: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_OutputDirectory {
            get {
                return ResourceManager.GetString("Log_OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源文件: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_SourceFile {
            get {
                return ResourceManager.GetString("Log_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spine 可执行文件: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_SpineExecutable {
            get {
                return ResourceManager.GetString("Log_SpineExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始转换: 的本地化字符串。
        /// </summary>
        internal static string Log_StartConversion {
            get {
                return ResourceManager.GetString("Log_StartConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标版本: {0} 的本地化字符串。
        /// </summary>
        internal static string Log_TargetVersion {
            get {
                return ResourceManager.GetString("Log_TargetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 Spine 可执行文件 的本地化字符串。
        /// </summary>
        internal static string SelectSpineExecutable {
            get {
                return ResourceManager.GetString("SelectSpineExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 Spine 项目文件 的本地化字符串。
        /// </summary>
        internal static string SelectSpineFile {
            get {
                return ResourceManager.GetString("SelectSpineFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始转换 的本地化字符串。
        /// </summary>
        internal static string StartConversion {
            get {
                return ResourceManager.GetString("StartConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spine 版本转换工具 的本地化字符串。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
